# Generated by Django 2.2.2 on 2019-06-11 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter genre title (Action, Horror, etc.)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter description of genre or leave it blank', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title of anime', max_length=200)),
                ('synonym', models.CharField(blank=True, help_text='Enter a title synonym (e.g. Japanese title)', max_length=200, null=True)),
                ('type', models.CharField(choices=[('T', 'TV'), ('M', 'Movie'), ('O', 'OVA'), ('S', 'Special')], help_text='Choice a type of anime (TV, Movie, OVA or Special)', max_length=10)),
                ('episodes', models.PositiveSmallIntegerField(help_text='Enter a number of episodes')),
                ('status', models.CharField(choices=[('C', 'Completed'), ('N', 'Not completed'), ('A', 'Announced')], help_text='Choice the current status of (e.g. Completed or not, announced)', max_length=15)),
                ('release_date', models.DateField(blank=True, help_text='Date of announce or first episode release', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project closing date or date of last episode release', null=True)),
                ('source', models.CharField(choices=[('M', 'Manga'), ('G', 'Game'), ('N', 'Novel'), ('O', 'Original')], help_text='The type of resource that became the basis of current anime', max_length=10)),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration of episode in minutes')),
                ('rating', models.CharField(choices=[('G', 'General audiences'), ('PG', 'Parental guidance suggested'), ('PG-13', 'Parents strongly cautioned'), ('R', 'Restricted'), ('NC-17', 'No One 17 & Under Admitted')], help_text='Choice MPAA film rating', max_length=30)),
                ('summary', models.TextField(help_text='Enter a summary', max_length=1000)),
                ('cover_url', models.URLField(help_text='Enter a cover URL address')),
                ('trailer_url', models.URLField(help_text='Enter a YouTube video trailer URL')),
                ('genre', models.ManyToManyField(help_text='Select the genres', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter studio name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='Enter your score')),
                ('message', models.TextField(help_text='Justify your opinion', max_length=500)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_movie', to='movies.Movie')),
                ('related_movies', models.ManyToManyField(related_name='related_movies', to='movies.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(blank=True, help_text='Select the studio that released that anime', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Studio'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
