# Generated by Django 2.2.2 on 2019-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveSmallIntegerField(default=23, help_text='Duration of episode in minutes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='episodes',
            field=models.PositiveSmallIntegerField(default=12, help_text='Enter a number of episodes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'General audiences'), ('PG', 'Parental guidance suggested'), ('PG-13', 'Parents strongly cautioned'), ('R', 'Restricted'), ('NC-17', 'No One 17 & Under Admitted')], default='R', help_text='Choice MPAA film rating', max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a summary', max_length=1000, null=True),
        ),
    ]
