# Generated by Django 2.2.2 on 2019-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190611_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='message',
            field=models.TextField(blank=True, help_text='Justify your opinion', max_length=500, null=True),
        ),
    ]
