# Generated by Django 2.2.2 on 2019-06-12 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20190611_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='allowed',
            field=models.BooleanField(default=False, help_text='Status of publication (only moderator can set True)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set the user that added this movie', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
