# Generated by Django 2.2.2 on 2019-06-12 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_auto_20190612_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(help_text='Enter genre title (Action, Horror, etc.)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='Choose related anime', null=True, related_name='_movie_related_+', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Enter a title of anime', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(help_text='Enter studio name', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('movie', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('movie', 'user')},
        ),
    ]
