# Generated by Django 2.2.2 on 2019-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190612_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='Choose related anime', related_name='_movie_related_+', to='movies.Movie'),
        ),
    ]
