# Generated by Django 2.2.2 on 2019-06-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190612_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-added_date']},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
