# Generated by Django 2.2.2 on 2019-06-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190613_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-added_date'], 'permissions': [('toggle_allowed_status', 'Toggle allowed status')]},
        ),
    ]
