# Generated by Django 2.2.2 on 2019-06-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190623_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-added_date'], 'permissions': [('can_toggle_allowed', 'Can toggle allowed')]},
        ),
    ]
